const { readFileSync, writeFileSync } = require('fs');

const OUTFILE = `${__dirname}/src/constants.ts`;

const TYPESCRIPT_VERSION = require('typescript').version;
const PACKAGE_VERSION = process.env.npm_package_version;

const get_git_hash = () => {
    const rev = readFileSync(`${__dirname}/.git/HEAD`).toString().trim();
    if (rev.includes(':')) return readFileSync(`${__dirname}/.git/${rev.substring(5)}`).toString();
    return rev;
};

const GIT_HASH = get_git_hash().slice(0, 7);

writeFileSync(OUTFILE,
`/** 
 * This file was autogenerated by gen_constants.js
 * ANY MODIFICATIONS WILL BE OVERWRITTEN
**/

export const TYPESCRIPT_VERSION = '${TYPESCRIPT_VERSION}';
export const PACKAGE_VERSION = '${PACKAGE_VERSION}';
export const GIT_HASH = '${GIT_HASH}';
`);